[package]
name = "intra_tests"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
intra = { git = "https://github.com/Verdex/intra", version = "0.1.0", tag = "release-0.1.0" }